name: ROS 2 Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ROS 2 Humble
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble

    - name: Setup cuda opencv
      run: |
        ls -la
        sudo bash installJetpack.sh

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          ros-humble-cv-bridge \
          ros-humble-image-transport \
          ros-humble-camera-info-manager \
          ros-humble-rclcpp \
          ros-humble-sensor-msgs \
          ros-humble-std-msgs \
          libopencv-dev
          ls -l /usr/include

    - name: Build with colcon
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Run tests (if any)
      run: |
        source install/setup.bash
        colcon test || echo "No tests found"
